spring:
  application:
    name: IoT-service
dubbo:
  application:
    name: IoT-service
  protocol:
    port: 20881
  registry:
    address: nacos://101.42.157.163:8848
    username: nacos
    password: nacos

influx:
  token: phqvNq5O0-Y0SqcxuQn8HSvqMHqOtEk92iI3Ig5jGkpsBuILR2E9G_4IJ0D_ygtSuMTcICAvAIkA8luM4zcLdg==

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
server:
  port: 18016

