spring:
  application:
    name: IoT-service
dubbo:
  application:
    name: IoT-service
  protocol:
    port: 20881
  registry:
    address: nacos://101.42.157.163:8848
    username: nacos
    password: nacos

influx:
  token: LJS2uOMQIhkDMF6W0dClZPC7HKLZ5hDt-o7cXBBiRSQp-Mup7EI-jBOT-xFDciR-nShTDNIl4MBDBUZdeCQubw==

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
server:
  port: 18016

