{
 "title": "IoT Service Monitoring Dashboard",
 "tags": [
  "iot-service",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "IoT服务核心线程数",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "executor_pool_core_threads{name=\"applicationTaskExecutor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IoT服务活跃线程",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "executor_active_threads{name=\"applicationTaskExecutor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IoT服务失败率 % (5m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0" }
   ]
  },
  {
   "title": "IoT服务虚拟机累计启动线程总数",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"iot-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IoT服务请求速率",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"iot-service\"}[5m])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "IoT服务95%响应时间",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_server_requests_seconds_bucket{job=\"iot-service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IoT服务JVM内存使用",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 10, "y": 5 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"iot-service\"}",
     "legendFormat": "{{area}} - {{id}}"
    }
   ]
  },
  {
   "title": "IoT服务Dubbo消费者请求速率",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "0" }
   ]
  },
  {
   "title": "IoT服务RocketMQ消息发送速率",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "0" }
   ]
  }
 ]
}